version: "3"
services:
    node-app:
        build:
            context: .
            args: 
                NODE_ENV: development
        volumes:
            - ./:/app:ro
            - /app/node_modules
        environment: 
            - NODE_ENV=development
            - MONGO_USER=username
            - MONGO_PASSWORD=password
        command: npm run dev

    mongo:
        environment: 
            - MONGO_INITDB_ROOT_USERNAME=username
            - MONGO_INITDB_ROOT_PASSWORD=password